joomla:
  image: mikemichel/joomla:3.7-beta3
  links:
    - joomladb:mysql
  ports:
    - 8080:80
  environment:
    JOOMLA_DB_NAME: joomla
    JOOMLA_DB_USER: admin
    JOOMLA_DB_PASSWORD: secret

joomladb:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: example
    MYSQL_USER: admin
    MYSQL_PASSWORD: secret
    MYSQL_DATABASE: joomla
