version: '2'
services:

  joomla:
    image: mikemichel/joomla:3.7-beta3
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_NAME: joomla
      JOOMLA_DB_USER: admin
      JOOMLA_DB_PASSWORD: secret
    depends_on:
      - mysql
    networks:
      - all

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: joomla
    networks:
      - all

networks:
  all:
